name: 'Run chrome'
description: 'It's run chrome'
runs:
  using: "composite"
  steps:
    - run: |
    chmod +x "${GITHUB_WORKSPACE}/runChrome.sh"
    ${GITHUB_WORKSPACE}/runChrome.sh
      shell: bash
